# Colors (Gruvbox dark)

# # Default colors
# [colors.primary]
# # hard contrast
# background  = '#1d2021'
# # background = '#282828'
# # soft contrast background = = '#32302f'
# foreground = '#ebdbb2'
#
# # Normal colors
# [colors.normal]
# black   = '#282828'
# red     = '#cc241d'
# green   = '#98971a'
# yellow  = '#d79921'
# blue    = '#458588'
# magenta = '#b16286'
# cyan    = '#689d6a'
# white   = '#a89984'
#
# # Bright colors
# [colors.bright]
# black   = '#928374'
# red     = '#fb4934'
# green   = '#b8bb26'
# yellow  = '#fabd2f'
# blue    = '#83a598'
# magenta = '#d3869b'
# cyan    = '#8ec07c'
# white   = '#ebdbb2'

# gruber dark colorscheme trying out
# Default colors 
[colors.primary]
  background= '#181818'
  foreground= '#e4e4ef'

# Normal colors
[colors.normal]
  black=   '#000000'
  red=     '#f43841'
  green=   '#73c936'
  yellow=  '#ffdd33'
  blue=    '#5f627f'
  magenta= '#9e95c7'
  cyan=    '#5f627f'
  white=   '#ffffff'

# Bright colors
[colors.bright]
  black=   '#282828'
  red=     '#ff4f58'
  green=   '#73c936'
  yellow=  '#ffdd33'
  blue=    '#96a6c8'
  magenta= '#9e95c7'
  cyan=    '#96a6c8'
  white=   '#ffffff'

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[window]
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
